#include<bits/stdc++.h>
using namespace std;
int main()
{
    int a ;
    float b;
    double c;
    char di;
    cout<<"Enter the int for the a: "<<endl;
    cin>>a;
    cout<<"Enter the float for the b: "<<endl;
    cin>>b;
    cout<<"Enter the double for the c: "<<endl;
    cin>>c;
    cout<<"Enter the char for the d: "<<endl;
    cin>>di;
    cout<<"the value of a : "<<a<<"the value of b : "<<b<<"the value of c :"<<c<<"the value of d :"<<di<<endl; 
}